[package]
name = "blurhash-generator"
version = "0.1.1"
edition = "2021"

[dependencies]
image = "0.25.4"
blurhash = "0.2.3"
clap = { version = "4.5.20", features = ["derive"] }
url = "2.5.2"
reqwest = { version = "0.12.9", features = ["blocking"] }
